# Generated by Django 2.1 on 2018-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='worksheets/')),
                ('isSolution', models.BooleanField()),
                ('worksheetNumber', models.IntegerField()),
                ('variablesAndFunctions', models.BooleanField()),
                ('controls', models.BooleanField()),
                ('wwpd', models.BooleanField()),
                ('environmentDiagrams', models.BooleanField()),
                ('higherOrderFunctions', models.BooleanField()),
                ('lambdaExpressions', models.BooleanField()),
                ('recursion', models.BooleanField()),
                ('treeRecursion', models.BooleanField()),
                ('dataAbstraction', models.BooleanField()),
                ('ordersOfGrowth', models.BooleanField()),
                ('pythonLists', models.BooleanField()),
                ('linkedLists', models.BooleanField()),
                ('mutableTrees', models.BooleanField()),
                ('nonloc', models.BooleanField()),
                ('oop', models.BooleanField()),
                ('scheme', models.BooleanField()),
                ('schemeLists', models.BooleanField()),
                ('tailRecursion', models.BooleanField()),
                ('interpreters', models.BooleanField()),
                ('macros', models.BooleanField()),
                ('iteratorsAndGenerators', models.BooleanField()),
                ('streams', models.BooleanField()),
                ('sequel', models.BooleanField()),
                ('midterm1', models.BooleanField()),
                ('midterm2', models.BooleanField()),
                ('final', models.BooleanField()),
            ],
        ),
    ]
